# Generated by Django 3.2.6 on 2021-08-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0002_courses_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='course_id',
            field=models.IntegerField(),
        ),
    ]
